name: themes
description: A new Flutter package project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: 1.14.1
  custom_lint: 0.6.7
  flutter_test:
    sdk: flutter
