blank_issues_enabled: false
contact_links:
    - name: Documentation (FAQ)
      url: https://github.com/hizuki-mimuro/Notoria/blob/development/guide/faq.md
      about: Please see our documentation for common questions and answers.
    - name: Documentation (Debugging)
      url: https://github.com/hizuki-mimuro/Notoria/blob/development/guide/debugging.md
      about: Please see our documentation for debugging tips.
    - name: Forum
      url: https://groups.google.com/g/hizuki-mimuro
      about: Ask and answer general questions here.
